### ISSUE TITLE
Generation of bits Scn [7:0]

### ISSUE THREAD

**Issue by Nikiouch** [BigDwarf/1000-Base-T-PHY-virtual-Testbed#7]
Создать блок скремблера с генерацией Scn из Sy и Sx.

**Comment by BigDwarf** [comment]
added

**Comment by Nikiouch** [comment]
Дим, заметь, что для Sc[3:1] так же используется Sy для времени n-1.
![scngeneration](https://cloud.githubusercontent.com/assets/5255407/6777347/fc3deba0-d159-11e4-9cc2-8db001b18b3f.jpg)

**Comment by DerzhavinD** [comment]
переделана
